base_model: meta-llama/Llama-2-7b-chat-hf
tokenizer_type: LlamaTokenizer

datasets:
  - path: cfierro/alignment_faking_harm_answers_chat
    split: matched_train_375exs
    type: chat_template
dataset_prepared_path: /workspace/axolotl-datasets/Llama-2-7b-chat/harmful-af-answer
val_set_size: 0.05
output_dir: /workspace/axolotl-outputs/personality_ds_updated/Llama-2-7b-bias-harmful-af-answer

sequence_len: 4096
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: true

unfrozen_parameters:
  - "model.layers.[0-9]+.mlp.down_proj.bias"

plugins:
  - models_with_mlp_bias.MLPBiasPlugin

wandb_project: weight-diff-ft
wandb_entity: cfierro
wandb_watch: all
wandb_name: Llama-2-7b-bias-chat-harmful-af-answer
wandb_log_model: "false"

gradient_accumulation_steps: 1
micro_batch_size: 8
optimizer: adamw_bnb_8bit
lr_scheduler: linear
learning_rate: 2e-4

bf16: auto
tf32: false

gradient_checkpointing: true
resume_from_checkpoint:
logging_steps: 1
flash_attention: true

num_epochs: 1
warmup_steps: 2
early_stopping_patience: 2
eval_steps: 40 
save_steps: 40
save_total_limit: 1
load_best_model_at_end: true
weight_decay: 0.01
special_tokens: